### PR TITLE
Update Docker images.

### PR DESCRIPTION
**Pull request by ssungwxx**
Fix elasticsearch version 7.12.2 -> 7.12.1

### CODE REVIEW

**Review by digikin — COMMENTED** [review]
Hey I just noticed that 7.13.1 just came out for Elasticsearch and Kibana want to test a new compose-file to merge?
https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
https://www.elastic.co/guide/en/kibana/current/docker.html

If not ill update it by this weekend.

**Comment by ssungwxx** [comment]
Hi
New version come out soon. Good news!
However, the version is in the README.md (7.12.2) is not exist version. I recommend merge and test next version. Some people confused like me.🥲

**Comment by digikin** [comment]
Ill fix the readme.  Do you want to try and test the new versions of the docker images and put in a merge?

**Comment by ssungwxx** [comment]
Of course. I'll try it this week and leave a comment.

**Comment by ssungwxx** [comment]
@digikin 
Hi there. PR updated. it works.

**Comment by digikin** [comment]
Good job!

**Pull request merged**
